name: Publish on GitHub Pages

on:
  push:
    branches: [ master ]
  workflow_run:
    workflows: ["Commit lib/posts"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Setup Deno environment
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Build site
        run: |
          deno run -A https://deno.land/x/lume/ci.ts --location=https://tabularelf.github.io/

      - name: Deploy
        uses: crazy-max/ghaction-github-pages@v2.0.1
        with:
          repo: tabularelf/tabularelf.github.io
          build_dir: _site
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_PAT: ${{ secrets.DEPLOY_KEY }}